name: BMI Calculator

on:
  push:
    branches:
      - main

jobs:
  calculating:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Wähle die passende Node.js-Version für Jest

      - name: Install Dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
